generator: admingenerator.generator.doctrine
params:
    model: Nutritionist\StoreBundle\Entity\Category
    namespace_prefix: Nutritionist
    bundle_name: StoreBundle
    fields: ~

builders:
    list:
        params:
            title: List for StoreBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New object for StoreBundle
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: YourModel.title }|"
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: YourModel.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    delete: ~
