generator: admingenerator.generator.doctrine
params:
    model: Nutritionist\StoreBundle\Entity\Food
    namespace_prefix: Nutritionist
    bundle_name: StoreBundle
    fields:
      category:
        label:   category name
        sort_on: category.name
        getter:  category.name

builders:
    list:
        params:
            title: List for Food
            display: [name,category]
            object_actions:
            actions:
                new: ~
    filters:
        params:
            display: [name,category]
    new:
        params:
            title: New object for Food
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Food.name }|"
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Food.name }|"
            display: ~
            actions:
                list: ~
                new: ~
    delete: ~
