<?php

namespace Nutritionist\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Goutte\Client;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    public function loadCategories($url = 'http://www.inran.it/646/tabelle_di_composizione_degli_alimenti.html'){

        $client = new Client();
        $crawler = $client->request('GET',$url);
        $nodes = $crawler->filter('#categoria');

        if ($nodes->count())
        {
            foreach($nodes->children() as $node){
                $category = new Category();
                $category->setName($node->nodeValue);
                $this->_em->persist($category);
            }
        }
        $this->_em->flush();
    }


}
