<?php

namespace Nutritionist\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FoodNutrientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodNutrientRepository extends EntityRepository
{

    public function loadFoodNutrient($url = 'http://www.inran.it/646/tabelle_di_composizione_degli_alimenti.html?alimento=&nutriente=tutti&categoria=tutte&quant=100&submitted1=TRUE&sendbutton=Cerca')
    {
        set_time_limit (14400);
        $em = $this->getEntityManager();
        $client = new Client();
        $crawler = $client->request('GET',$url, array('curl.options' => array(CURLOPT_CONNECTTIMEOUT=> 90,CURLOPT_CONNECTTIMEOUT_MS=>15000)));
        $nodes = $crawler->filter('.elencoalim');
        if ($nodes->count())
        {
            foreach($nodes as $node){

                $href="http://www.inran.it";
                $href .= $node->firstChild->getAttribute('href');
                $link = new Link($node->firstChild,$href);
                $crawler_link = $client->click($link);
                $tab1 = $crawler_link->filter('.Tabella1');

                // Food
                $trs = $tab1->first()->children();
                $tr = $trs->first();
                $th = $tr->children();
                $food_name = $th->text(); //food

                $food_repo = $this->getDoctrine()->getRepository('NutritionistStoreBundle:Food');
                $food = $food_repo->findOneByName($food_name);

                foreach($tab1->eq(1)->filterXPath('//tr') as $tr_node){
                    if(is_object($tr_node->childNodes->item(0)) and $tr_node->childNodes->item(0)->tagName == 'td'){
                        $td = $tr_node->childNodes->item(0);
                        $nutrient_name = $this->ediblePartMisureUnit($td->textContent);

                        $nutrient = $em->getRepository('NutritionistStoreBundle:Nutrient')->findByNameLike($nutrient_name);
                    }
                    else{
                        continue;
                    }

                    if(is_object($tr_node->childNodes->item(1)) and $tr_node->childNodes->item(1)->nodeName == 'td'){
                        $value = 0;
                        $value = trim($tr_node->childNodes->item(1)->textContent);
                        if(is_numeric($value)){
                            $value = $value;
                            $note = "";
                        }
                        elseif(is_string($value)){
                            $note = $value;
                            $value = 0;
                        }
                        else{
                            $note = $value;
                            $value = 0;

                        }
                    }
                    $foodNutrient = new FoodNutrient();
                    $foodNutrient->setFood($food);
                    $foodNutrient->setNutrient($nutrient);
                    $foodNutrient->setFoodNutrient(number_format($value,2,'.',','));
                    $foodNutrient->setNote($note);
                    $em->persist($foodNutrient);
                    $em->flush();
                }
            }
        }

    }
}
