<?php

namespace Nutritionist\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Goutte\Client;
use Symfony\Component\Form\Exception\Exception;

/**
 * NutrientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NutrientRepository extends EntityRepository
{

    public function loadNutrients($url = 'http://www.inran.it/646/tabelle_di_composizione_degli_alimenti.html'){
        $client = new Client();
        $crawler = $client->request('GET',$url);
        $nodes = $crawler->filter('#nutriente');
        if ($nodes->count())
        {
            if ($nodes->count())
            {
                foreach($nodes->children() as $node){
                    $nutrient = new Nutrient();
                    $nutrient->setName($node->nodeValue);
                    $this->_em->persist($nutrient);
                }
            }
        }
        $this->_em->flush();
    }

    public function findByNameLike($str = ''){
        if(strlen($str)){

            $em = $this->getEntityManager();
            $query = $em->createQuery('SELECT n FROM NutritionistStoreBundle:Nutrient n WHERE n.name like :name')->setParameter('name', trim($str).'%');
            try{
                $nutrient = $query->getSingleResult();
            }
            catch(\Exception $e){
                return new Nutrient();
            }
            return $nutrient;

        }
    }
}


