NutritionistStoreBundle_admin_nutritionist_store_bundle_NutrientAdmin:
    resource: "@NutritionistStoreBundle/Controller/NutrientAdmin/"
    type:     admingenerator
    prefix:   /admin/nutritionist_store_bundle/NutrientAdmin

NutritionistStoreBundle_admin_nutritionist_store_bundle_FoodAdmin:
    resource: "@NutritionistStoreBundle/Controller/FoodAdmin/"
    type:     admingenerator
    prefix:   /admin-food

NutritionistStoreBundle_admin_nutritionist_store_bundle_CategoryAdmin:
    resource: "@NutritionistStoreBundle/Controller/CategoryAdmin/"
    type:     admingenerator
    prefix:   /admin-category

nutritionist_user:
    resource: "@NutritionistUserBundle/Controller/"
    type:     annotation
    prefix:   /

nutritionist_admin:
    resource: "@NutritionistAdminBundle/Controller/"
    type:     annotation
    prefix:   /

nutritionist_store:
    resource: "@NutritionistStoreBundle/Controller/"
    type:     annotation
    prefix:   /

dashboard_welcome:
    pattern:  /dashboard
    defaults: { _controller: NutritionistStoreBundle/Category/New}

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

