NutritionistStoreBundle_admin_nutritionist_store_bundle_FoodAdmin:
    resource: "@NutritionistStoreBundle/Controller/FoodAdmin/"
    type:     admingenerator
    prefix:   /admin/nutritionist_store_bundle/FoodAdmin

NutritionistStoreBundle_admin_nutritionist_store_bundle_CategoryAdmin:
    resource: "@NutritionistStoreBundle/Controller/CategoryAdmin/"
    type:     admingenerator
    prefix:   /admin/nutritionist_store_bundle/CategoryAdmin

nutritionist_user:
    resource: "@NutritionistUserBundle/Controller/"
    type:     annotation
    prefix:   /

nutritionist_admin:
    resource: "@NutritionistAdminBundle/Controller/"
    type:     annotation
    prefix:   /

nutritionist_store:
    resource: "@NutritionistStoreBundle/Controller/"
    type:     annotation
    prefix:   /

dashboard_welcome:
    pattern:  /dashboard
    defaults: { _controller: NutritionistStoreBundle/Category/New}

